#!/bin/bash
set -eu

PACKAGE="$1"
OUT="$2"
shift 2

URL="https://aur.archlinux.org/cgit/aur.git/snapshot/$PACKAGE.tar.gz"

DIR="$(mktemp -d)"
_cleanup() {
	rm -rf "$DIR"
}
trap _cleanup EXIT

cd "$DIR"

curl -sSL "$URL" | tar xz --strip-components 1
env EUID=1 makepkg -sc --noconfirm "$@"

for pkg in $(env EUID=1 makepkg --packagelist); do
	pkgfile=$pkg.pkg*
	if [ ! -f $pkgfile ]; then
		echo "Unable to find $pkg" >&2
		exit 1
	fi

	cp $pkgfile "$OUT"
done
