#!/bin/bash
set -eu

FLAG_PACKAGES=(alpine-base tzdata)
while getopts ":p:" opt; do
	case $opt in
		p) # --packages "openssh git"
			FLAG_PACKAGES+=($OPTARG)
			;;
		\?)
			echo "Invalid option: -$OPTARG" >&2
			exit 1
			;;
	esac
done
shift $((OPTIND-1))

FLAG_OUT="$1"
shift

ALPINE_MIRRORS=http://nl.alpinelinux.org/alpine/MIRRORS.txt

if [ -z "${ALPINE_MIRROR-}" ]; then
	ALPINE_MIRROR=$(curl -fsSL "$ALPINE_MIRRORS" | shuf -n 1)
fi
ALPINE_ARCH=x86_64
ALPINE_VERSION=v3.3
APK_TOOLS_VERSION=2.6.5-r1
APK_TOOLS_STATIC="$ALPINE_MIRROR/$ALPINE_VERSION/main/$ALPINE_ARCH/apk-tools-static-$APK_TOOLS_VERSION.apk"

mkdir -p "$FLAG_OUT"
curl -fsSL "$APK_TOOLS_STATIC" | tar xz -C "$FLAG_OUT/" sbin/apk.static

CAGE=(cage exec -e http_proxy -e https_proxy)
APK_FLAGS=("$FLAG_OUT" /sbin/apk.static
	-X "$ALPINE_MIRROR/$ALPINE_VERSION/main" -U --no-cache --allow-untrusted --root / --no-progress --quiet
)
APK=("${CAGE[@]}" "${APK_FLAGS[@]}")
"${APK[@]}" add --initdb

"${APK[@]}" add "${FLAG_PACKAGES[@]}"
if [ -f "$FLAG_OUT/bin/bbsuid" ]; then
	chmod u+r "$FLAG_OUT/bin/bbsuid"
fi
